# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec194980a7bf05319735010979c61b11fcf83fc3364f424fcad4d1e0f6bc7b9b74aca78a12c2ae13fb5923244d7a70dea0fbea19132bd77fe7726b99d5bbee69

test:
  secret_key_base: 490fe01b2d2dcb3f491d0c6c1f5f740d4f68cb650e4b2e38e24469df8f58f48af328cd2a1994befa026be8ea0ee6dac04e5ec5ef576843a3fbc80f94a113d794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
